version: '3.8'

services:
  guardian-connector:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Build arguments - these will be read from .env file
        NUXT_COMMUNITY_NAME: ${NUXT_COMMUNITY_NAME}
        NUXT_AUTH0_DOMAIN: ${NUXT_AUTH0_DOMAIN}
        NUXT_AUTH0_CLIENT_ID: ${NUXT_AUTH0_CLIENT_ID}
        NUXT_AUTH0_REDIRECT_URI: ${NUXT_AUTH0_REDIRECT_URI}
        NUXT_SUPERSET_ENABLED: ${NUXT_SUPERSET_ENABLED}
        NUXT_WINDMILL_ENABLED: ${NUXT_WINDMILL_ENABLED}
        NUXT_EXPLORER_ENABLED: ${NUXT_EXPLORER_ENABLED}
        NUXT_FILES_BROWSER_ENABLED: ${NUXT_FILES_BROWSER_ENABLED}
        # Public build arguments (for client-side access)
        NUXT_PUBLIC_COMMUNITY_NAME: ${NUXT_COMMUNITY_NAME}
        NUXT_PUBLIC_AUTH0_DOMAIN: ${NUXT_AUTH0_DOMAIN}
        NUXT_PUBLIC_AUTH0_CLIENT_ID: ${NUXT_AUTH0_CLIENT_ID}
        NUXT_PUBLIC_AUTH0_REDIRECT_URI: ${NUXT_AUTH0_REDIRECT_URI}
        NUXT_PUBLIC_SUPERSET_ENABLED: ${NUXT_SUPERSET_ENABLED}
        NUXT_PUBLIC_WINDMILL_ENABLED: ${NUXT_WINDMILL_ENABLED}
        NUXT_PUBLIC_EXPLORER_ENABLED: ${NUXT_EXPLORER_ENABLED}
        NUXT_PUBLIC_FILES_BROWSER_ENABLED: ${NUXT_FILES_BROWSER_ENABLED}
    ports:
      - "8080:8080"
    environment:
      # Runtime environment variables (also from .env)
      NUXT_COMMUNITY_NAME: ${NUXT_COMMUNITY_NAME}
      NUXT_AUTH0_DOMAIN: ${NUXT_AUTH0_DOMAIN}
      NUXT_AUTH0_CLIENT_ID: ${NUXT_AUTH0_CLIENT_ID}
      NUXT_AUTH0_REDIRECT_URI: ${NUXT_AUTH0_REDIRECT_URI}
      NUXT_SUPERSET_ENABLED: ${NUXT_SUPERSET_ENABLED}
      NUXT_WINDMILL_ENABLED: ${NUXT_WINDMILL_ENABLED}
      NUXT_EXPLORER_ENABLED: ${NUXT_EXPLORER_ENABLED}
      NUXT_FILES_BROWSER_ENABLED: ${NUXT_FILES_BROWSER_ENABLED}
      # Public runtime environment variables
      NUXT_PUBLIC_COMMUNITY_NAME: ${NUXT_COMMUNITY_NAME}
      NUXT_PUBLIC_AUTH0_DOMAIN: ${NUXT_AUTH0_DOMAIN}
      NUXT_PUBLIC_AUTH0_CLIENT_ID: ${NUXT_AUTH0_CLIENT_ID}
      NUXT_PUBLIC_AUTH0_REDIRECT_URI: ${NUXT_AUTH0_REDIRECT_URI}
      NUXT_PUBLIC_SUPERSET_ENABLED: ${NUXT_SUPERSET_ENABLED}
      NUXT_PUBLIC_WINDMILL_ENABLED: ${NUXT_WINDMILL_ENABLED}
      NUXT_PUBLIC_EXPLORER_ENABLED: ${NUXT_EXPLORER_ENABLED}
      NUXT_PUBLIC_FILES_BROWSER_ENABLED: ${NUXT_FILES_BROWSER_ENABLED}
    env_file:
      - .env 