# Use the official Node.js image from DockerHub
FROM node:20.15.0-slim

# Set the working directory
RUN mkdir -p /app
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy package.json and package-lock.json into the container
COPY package*.json  /app/

# Install dependencies
RUN pnpm install

# Copy the application files into the container
COPY . /app

# Build arguments for environment variables
ARG NUXT_COMMUNITY_NAME
ARG NUXT_AUTH0_DOMAIN
ARG NUXT_AUTH0_CLIENT_ID
ARG NUXT_AUTH0_REDIRECT_URI
ARG NUXT_SUPERSET_ENABLED
ARG NUXT_WINDMILL_ENABLED
ARG NUXT_EXPLORER_ENABLED
ARG NUXT_FILES_BROWSER_ENABLED
# Public build arguments (for client-side access)
ARG NUXT_PUBLIC_COMMUNITY_NAME
ARG NUXT_PUBLIC_AUTH0_DOMAIN
ARG NUXT_PUBLIC_AUTH0_CLIENT_ID
ARG NUXT_PUBLIC_AUTH0_REDIRECT_URI
ARG NUXT_PUBLIC_SUPERSET_ENABLED
ARG NUXT_PUBLIC_WINDMILL_ENABLED
ARG NUXT_PUBLIC_EXPLORER_ENABLED
ARG NUXT_PUBLIC_FILES_BROWSER_ENABLED

# Set environment variables for build
ENV NUXT_COMMUNITY_NAME=$NUXT_COMMUNITY_NAME
ENV NUXT_AUTH0_DOMAIN=$NUXT_AUTH0_DOMAIN
ENV NUXT_AUTH0_CLIENT_ID=$NUXT_AUTH0_CLIENT_ID
ENV NUXT_AUTH0_REDIRECT_URI=$NUXT_AUTH0_REDIRECT_URI
ENV NUXT_SUPERSET_ENABLED=$NUXT_SUPERSET_ENABLED
ENV NUXT_WINDMILL_ENABLED=$NUXT_WINDMILL_ENABLED
ENV NUXT_EXPLORER_ENABLED=$NUXT_EXPLORER_ENABLED
ENV NUXT_FILES_BROWSER_ENABLED=$NUXT_FILES_BROWSER_ENABLED
# Public environment variables
ENV NUXT_PUBLIC_COMMUNITY_NAME=$NUXT_PUBLIC_COMMUNITY_NAME
ENV NUXT_PUBLIC_AUTH0_DOMAIN=$NUXT_PUBLIC_AUTH0_DOMAIN
ENV NUXT_PUBLIC_AUTH0_CLIENT_ID=$NUXT_PUBLIC_AUTH0_CLIENT_ID
ENV NUXT_PUBLIC_AUTH0_REDIRECT_URI=$NUXT_PUBLIC_AUTH0_REDIRECT_URI
ENV NUXT_PUBLIC_SUPERSET_ENABLED=$NUXT_PUBLIC_SUPERSET_ENABLED
ENV NUXT_PUBLIC_WINDMILL_ENABLED=$NUXT_PUBLIC_WINDMILL_ENABLED
ENV NUXT_PUBLIC_EXPLORER_ENABLED=$NUXT_PUBLIC_EXPLORER_ENABLED
ENV NUXT_PUBLIC_FILES_BROWSER_ENABLED=$NUXT_PUBLIC_FILES_BROWSER_ENABLED

# Build the application
RUN pnpm run build

# Expose and set port 8080
EXPOSE 8080
ENV NITRO_PORT=8080

# Run the application
ENTRYPOINT ["node", ".output/server/index.mjs"]